version: '3.7'

services:
  database:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: webmaster
      POSTGRES_USER: webmaster
      POSTGRES_DB: symfony_learn
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      test-network:
        ipv4_address: 192.168.220.7

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - database
    networks:
      test-network:
        ipv4_address: 192.168.220.8

volumes:
  database:
    driver: 'local'

networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28